### ISSUE TITLE
Issue on preprocessing cresci_15 for BotRGCN

### ISSUE THREAD

**Issue by von1000** [LuoUndergradXJTU/TwiBot-22#23]
Thank you for sharing your code!
I'm reproducing BotRGCN on dataset cresci_15 using your code. However, after running "preprocess_1.py", in "each_user_tweets.npy", user_tweets for each user are empty. I found this is because all 'source_id'  lead to KeyError in line 215. How can I fix this bug? Thank you!

**Comment by leopoldwhite** [comment]
> Thank you for sharing your code! I'm reproducing BotRGCN on dataset cresci_15 using your code. However, after running "preprocess_1.py", in "each_user_tweets.npy", user_tweets for each user are empty. I found this is because all 'source_id' lead to KeyError in line 215. How can I fix this bug? Thank you!

Hi, thank you for your interest in our work! "preprocess_1.py" is reuploaded and this bug is fixed now. Sorry for the inconvenience.
https://github.com/LuoUndergradXJTU/TwiBot-22/blob/f2f46877e8fb5a141288d86adb2d3d9e4e0fd6ef/src/BotRGCN/cresci_15/preprocess_1.py#L210-L212

**Comment by von1000** [comment]
Thank you for your quick response!
After running the updated preprocess code, I'm still a little confused about the generated "each_user_tweets". In this file, only the first user has corresponding tweets, the tweets for other users are all empty. The picture below is part of the "each_user_tweets". Am I doing something wrong?
<img width="1360" alt="Screen Shot 2023-02-13 at 9 59 02 AM" src="https://user-images.githubusercontent.com/8852062/218354524-274fe864-07cc-4386-9bac-0e17ccaa2a92.png">

**Comment by BunsenFeng** [comment]
@leopoldwhite

**Comment by leopoldwhite** [comment]
Sorry for the inconvenience. The code to get all users' tweets should be:
![image](https://user-images.githubusercontent.com/92447967/218380295-43e51611-3a5c-4269-bec9-01fe60b77251.png)

However, to save excution time and storage, the updated code only save the index of each tweet (mapped target_id) into each_user_tweets.npy,
https://github.com/LuoUndergradXJTU/TwiBot-22/blob/b2b9ee86084a590531f9e02529e2502e6603acee/src/BotRGCN/cresci_15/preprocess_1.py#L211-L212
which can be easily used in `preprocess_2.py`.

**Comment by znagzanglong** [comment]
When I tried to train BotRGCN, I encountered a problem. I didn’t know what description.npy was.

**Comment by znagzanglong** [comment]
When I tried to train BotRGCN, I encountered a problem. I didn’t know what description.npy was.                                               
    Loading labels...   Finished
Traceback (most recent call last):
  File "C:\kust\xuesu\code\TwiBot-22-master\TwiBot-22-master\src\BotRGCN\cresci_15\train.py", line 24, in <module>
    des_tensor,tweets_tensor,num_prop,category_prop,edge_index,edge_type,labels,train_idx,val_idx,test_idx=dataset.dataloader()
  File "C:\kust\xuesu\code\TwiBot-22-master\TwiBot-22-master\src\BotRGCN\cresci_15\Dataset.py", line 344, in dataloader
    des_tensor=self.Des_embbeding()
  File "C:\kust\xuesu\code\TwiBot-22-master\TwiBot-22-master\src\BotRGCN\cresci_15\Dataset.py", line 72, in Des_embbeding
    description=np.load(self.root+'description.npy',allow_pickle=True)
  File "C:\Users\Administrator\anaconda3\envs\TwiBot-22\lib\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './processed_data/description.npy'

**Comment by imempty** [comment]
> When I tried to train BotRGCN, I encountered a problem. I didn’t know what description.npy was. Loading labels... Finished Traceback (most recent call last): File "C:\kust\xuesu\code\TwiBot-22-master\TwiBot-22-master\src\BotRGCN\cresci_15\train.py", line 24, in des_tensor,tweets_tensor,num_prop,category_prop,edge_index,edge_type,labels,train_idx,val_idx,test_idx=dataset.dataloader() File "C:\kust\xuesu\code\TwiBot-22-master\TwiBot-22-master\src\BotRGCN\cresci_15\Dataset.py", line 344, in dataloader des_tensor=self.Des_embbeding() File "C:\kust\xuesu\code\TwiBot-22-master\TwiBot-22-master\src\BotRGCN\cresci_15\Dataset.py", line 72, in Des_embbeding description=np.load(self.root+'description.npy',allow_pickle=True) File "C:\Users\Administrator\anaconda3\envs\TwiBot-22\lib\site-packages\numpy\lib\npyio.py", line 427, in load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: './processed_data/description.npy'

same question
